import { defineConfig, presetIcons, presetUno } from 'unocss'

export default defineConfig({
  presets: [presetUno({
    dark: 'class'
  }), presetIcons()],
  theme: {
    colors: {
      background: 'var(--background)',
      foreground: 'var(--foreground)',
      surface: 'var(--surface)',
      'surface-elevated': 'var(--surface-elevated)',
      card: 'var(--card)',
      'card-foreground': 'var(--card-foreground)',
      popover: 'var(--popover)',
      'popover-foreground': 'var(--popover-foreground)',
      primary: 'var(--primary)',
      'primary-foreground': 'var(--primary-foreground)',
      'primary-glow': 'var(--primary-glow)',
      secondary: 'var(--secondary)',
      'secondary-foreground': 'var(--secondary-foreground)',
      muted: 'var(--muted)',
      'muted-foreground': 'var(--muted-foreground)',
      accent: 'var(--accent)',
      'accent-foreground': 'var(--accent-foreground)',
      destructive: 'var(--destructive)',
      'destructive-foreground': 'var(--destructive-foreground)',
      success: 'var(--success)',
      'success-foreground': 'var(--success-foreground)',
      warning: 'var(--warning)',
      'warning-foreground': 'var(--warning-foreground)',
      border: 'var(--border)',
      input: 'var(--input)',
      ring: 'var(--ring)',
      key: 'var(--key)',
      'key-foreground': 'var(--key-foreground)',
      'key-active': 'var(--key-active)',
    },
    borderRadius: {
      sm: 'calc(var(--radius) - 4px)',
      md: 'calc(var(--radius) - 2px)',
      lg: 'var(--radius)',
      xl: 'calc(var(--radius) + 4px)',
      '2xl': 'calc(var(--radius) + 8px)',
      '3xl': 'calc(var(--radius) + 12px)',
    },
    fontFamily: {
      display: '-apple-system, BlinkMacSystemFont, "Segoe UI Variable Display", "Segoe UI", system-ui, ui-sans-serif, sans-serif',
      sans: '-apple-system, BlinkMacSystemFont, "Segoe UI Variable Text", "Segoe UI", system-ui, ui-sans-serif, sans-serif',
      mono: 'ui-monospace, "SF Mono", "Cascadia Code", "Cascadia Mono", Consolas, Menlo, monospace',
    },
  },
  shortcuts: [
    ['l-btn', 'rounded-full p-2 capitalize'],
    ['l-btn-primary', 'bg-primary text-primary-foreground'],
    ['l-btn-secondary', 'text-primary border border-primary'],
    ['success-prose', 'text-success'],
    ['success-bg', 'bg-success text-success-foreground'],
    ['warning-prose', 'text-warning'],
    ['warning-bg', 'bg-warning text-warning-foreground'],
    ['info-prose', 'text-accent'],
    ['info-bg', 'bg-accent text-accent-foreground'],
    ['danger-prose', 'text-destructive'],
    ['danger-bg', 'bg-destructive text-destructive-foreground'],
  ],
})
