// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
export type CategoryProgressStat = { category: string, completedLessons: number, totalLessons: number, };
