// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Lesson } from "./Lesson";

export type CategoryWithLessons = { category: string, lessons: Array<Lesson>, tests: Array<Lesson>, isAvailable: boolean, };
