// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Lesson = { id: number, title: string, content: string, difficulty: string, language: string, createdAt: string | null, updatedAt: string | null, };
