// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LessonTest = { id: number, lessonId: number, title: string, content: string, passingWpm: number, accuracyThreshold: number, createdAt: string | null, };
