// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecentCompletion = { id: number, lessonId: number, lessonTitle: string, category: string, wpm: number, accuracy: number, grade: string, durationSeconds: number, completedAt: string, };
