// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TreeStageInfo = { stage: number, stageName: string, stageDescription: string, progressPercentage: number, nextMilestoneHint: string, foliageDensity: number, bloomCount: number, totalBranches: number, };
