// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type User = { id: number, name: string, username: string, createdAt: string | null, lastActive: string | null, keyboardType: string | null, language: string | null, theme: string | null, lessonDifficulty: string | null, };
