// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type User = { id: number, name: string, avatar: string, language: string, lessonDifficulty: string, createdAt: string | null, lastActive: string | null, };
