// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategoryProgressStat } from "./CategoryProgressStat";
import type { DailyActivityStat } from "./DailyActivityStat";
import type { GradeCount } from "./GradeCount";
import type { RecentCompletion } from "./RecentCompletion";
import type { StreakInfo } from "./StreakInfo";
import type { TreeStageInfo } from "./TreeStageInfo";

export type UserStatistics = { avgWpm: number, avgAccuracy: number, bestWpm: number, totalTimeSeconds: number, totalCompletions: number, totalLessonsCompleted: number, gradeDistribution: Array<GradeCount>, categoryProgress: Array<CategoryProgressStat>, recentActivity: Array<RecentCompletion>, dailyTrends: Array<DailyActivityStat>, streakInfo: StreakInfo, treeStage: TreeStageInfo, };
