// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type User = { id: number, name: string, username: string, created_at: string | null, last_active: string | null, keyboard_type: string | null, language: string | null, theme: string | null, lesson_difficulty: string | null, };
