// THIS FILE IS AUTO-GENERATED BY CARGO TESTS! DO NOT EDIT!

import { core } from '@tauri-apps/api';

export type TauriCommands = {
    exit_app: {
        returns: void,
        args: undefined
    }
};

export function invoke<T extends keyof TauriCommands>(
    cmd: T,
    args: TauriCommands[T]['args'] extends undefined ? undefined : TauriCommands[T]['args']
): Promise<TauriCommands[T]['returns']> {
    return core.invoke(cmd, args);
}
