// THIS FILE IS AUTO-GENERATED BY CARGO TESTS! DO NOT EDIT!

import { core } from '@tauri-apps/api';
import type { CategoryWithLessons, Lesson, NewUser, User, UserStatistics } from './bindings';

export type TauriCommands = {
    get_user_statistics: {
        returns: UserStatistics,
        args: { userId: number, difficulty: string }
    },
    get_lessons_by_difficulty: {
        returns: Lesson[],
        args: { difficulty: string }
    },
    get_lesson_tests: {
        returns: Lesson[],
        args: { id: number }
    },
    complete_lesson: {
        returns: void,
        args: { userId: number, lessonId: number, wpm: number, accuracy: number, grade: string, durationSeconds: number }
    },
    get_completed_lessons: {
        returns: number[],
        args: { userId: number }
    },
    get_lessons_by_categories: {
        returns: CategoryWithLessons[],
        args: { difficulty: string, userId: number }
    },
    get_category_tests: {
        returns: Lesson[],
        args: { category: string, difficulty: string }
    },
    get_lesson_by_id: {
        returns: Lesson,
        args: { lessonId: number }
    },
    get_all_users: {
        returns: User[],
        args: undefined
    },
    add_user: {
        returns: void,
        args: { body: NewUser }
    },
    update_user_preferences: {
        returns: User,
        args: { userId: number, language: string, lessonDifficulty: string }
    },
    exit_app: {
        returns: void,
        args: undefined
    }
};

export function invoke<T extends keyof TauriCommands>(
    cmd: T,
    args?: TauriCommands[T]['args']
): Promise<TauriCommands[T]['returns']> {
    return core.invoke(cmd, args);
}
