// THIS FILE IS AUTO-GENERATED BY CARGO TESTS! DO NOT EDIT!

import { core } from '@tauri-apps/api';

export type TauriCommands = {
    get_lessons_by_difficulty: {
        returns: Lesson[],
        args: { difficulty: string }
    },
    get_lesson_tests: {
        returns: LessonTest[],
        args: { id: number }
    },
    get_all_users: {
        returns: User[],
        args: undefined
    },
    add_user: {
        returns: void,
        args: { body: NewUser }
    },
    exit_app: {
        returns: void,
        args: undefined
    }
};

export function invoke<T extends keyof TauriCommands>(
    cmd: T,
    args?: TauriCommands[T]['args']
): Promise<TauriCommands[T]['returns']> {
    return core.invoke(cmd, args);
}
