// Generated by diesel_ext

use chrono::NaiveDateTime;
use diesel::prelude::{Insertable, Queryable};
use serde::{Deserialize, Serialize};
use ts_rs::TS;


#[derive(Insertable, Queryable, Debug, Serialize,  Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
#[diesel(table_name = crate::db::schema::tests)]
pub struct LessonTest {
    pub id: i32,
    pub lesson_id: i32,
    pub title: String,
    pub content: String,
    pub passing_wpm: i32,
    pub accuracy_threshold: i32,
    #[ts(type = "string | null")]
    pub created_at: Option<NaiveDateTime>,
}

