// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use chrono::NaiveDateTime;
use diesel::{prelude::Queryable, Selectable};

#[derive(Queryable, Selectable, Debug)]
#[diesel(table_name = crate::db::schema::users)]
pub struct User {
    pub id: i32,
    pub name: String,
    pub username: String,
    pub created_at: Option<NaiveDateTime>,
    pub last_active: Option<NaiveDateTime>,
    pub keyboard_type: Option<String>,
    pub language: Option<String>,
    pub theme: Option<String>,
    pub lesson_difficulty: Option<String>,
}
